### ISSUE TITLE
Standardize C builds using Makefiles and include instructions for local builds

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry-holding/device-opcua-c#25]
In the main repository we have the Go repositories using Makefiles to standardize their build processes on the targets; `build`, `test`, `docker` and `clean`. So far the C repositories are not using this same pattern and it is slowing us down for the build infrastructure and releases. 

Example of the Go Makefile: https://github.com/edgexfoundry/device-sdk-go/blob/master/Makefile

I'm not seeing the ability to hook Codecov into the the C builds as result. To use our current process we need a coverage report to be created using `gcov`. This is shown in the Codecov example for C here: https://github.com/codecov/example-c

The dependency on a VERSION file should be removed. We are removing that requirement from the build infrastructure in Geneva and keeping it will hinder us moving forward.

**Comment by lranjbar** [comment]
@jpwhitemn @jamesrgregg @ernestojeda Two years later... do you know if this is still relevant? :)

**Comment by ernestojeda** [comment]
@lranjbar Hey! This is somewhat still relevant. However, I think this issue belongs in edgex-global-pipelines. It can be closed and I will move it over there to track it. Thanks.

**Comment by lranjbar** [comment]
@ernestojeda Hey! I know long time no see. 😃 Happy new year too 🎉  I'll go ahead and close it and you can move it over to where it is easier to track?
